services:
  mariadb:
    image: mariadb:11.4 # LTS at 25. 12. 2025
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  habittracker:
    build:
      context: .
      dockerfile: Dockerfile
    #volumes:
    #  - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mariadb
