services:
  mariadb:
    image: mariadb:11.4 # LTS at 25. 12. 2025
    restart: on-failure:2
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    profiles: ["prod", "dev"]

  phpmyadmin:
    image: phpmyadmin
    restart: on-failure:2
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    profiles: ["dev"]

  fuelstats:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mariadb
    restart: on-failure:2
    profiles: ["prod"]
